### PR TITLE
mongoose get donors

### PR DESCRIPTION
**Pull request by devTy33**
# Description

Created the donors.ts file to get all donors from data base
## Relevant issue(s)
23

22
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have assigned reviewers to this PR

### CODE REVIEW

**Comment by alay10** [comment]
Please assign me and one other person to this PR

**Comment by Manan-dev** [comment]
Go ahead and fix the merge conflict, then I can test and merge it. It happened because Trishu also had to access the same file for this Create Donors code. We would need both your code and his code in that file I believe.

**Comment by alay10** [comment]
I believe that your code should work but there is an issue due to a bug in the schema. I fixed this in main and when I tested it after pulling from main it worked.

**Review by alay10 — APPROVED** [review]

**Comment by alay10** [comment]
Merge without another approval due to @Manan-dev approving of it verbally.

**Pull request merged**
