### PR TITLE
Alankha/create page to add item #53

### PR DESCRIPTION
**Pull request by AlanKha**
# Description
Implimented a page to add items. located at ```http://localhost:3000/item/add```
## Relevant issue(s)

#53 Create page to add an Item

## Questions
-Not sure if category should be a textinput or a dropdown menu.
## Type of change
- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have assigned reviewers to this PR

### CODE REVIEW

**Review by Manan-dev — APPROVED** [review]
LGTM!

**Review by alay10 — COMMENTED** [review]
This looks really great. I will figure it out more but you will need to try use as little css as possible and instead use the MUI options for that. I will tell you more once I know more about it.

**Review by andlrutt — DISMISSED** [review]
Sorry for the confusion on Figma, we really should write up some documentation the team can reference for the designer workflow. You generally won't be able to pull direct css values from there, they are automatically generated based on what the designer creates. Your goal is really just to emulate the look.

We also should write some documentation on MUI 😄. We use it because, aside from positioning, you don't really need to think about css. The proportions are guaranteed to look good. I won't comment on every css block here, but I'll leave you with some general guidelines:
1. Use MUI wherever an MUI component exists
2. Use inline styling when it's needed, no css file (this is hack4impact's coding style guidelines). 
3. If able, use properties from an MUI component's API (scroll to the bottom on its MUI page). Otherwise, use `sx={{ //styles go here }}` if you need to add css properties to an MUI component.
4. Try to avoid positioning/sizing using `px`, this leads to a lot of 'magic numbers' (Would `57px` _really_ not work instead of `56px`?). MUI has a great built in [spacing system ](https://mui.com/system/spacing/)

Try removing all of the CSS styling and adding it incrementally to the individual components to see what's needed, some may be redundant. Same with the MUI component properties, some may not be needed (`margin='normal'` and all the `id` props, for example)

**Comment by AlanKha** [comment]
Okay, so I got rid of the css file, and tried to use as much mui as possible. There are some things that I could not completely get rid of like ```position: 'absolute'```, but I've moved them all into the sx portion of the box.

I also made it so that min/max value could not be negative; If a negative value is entered, it defaults to 0.

**Comment by AlanKha** [comment]
I think the topbar and vector will need to be adjusted after the sidebar is implemented, but It's too early to tell.

**Review by alay10 — APPROVED** [review]
Looks good to me! Thanks for all the hard work on this one!

**Review by Manan-dev — APPROVED** [review]
Looks good to me!

**Review by AlanKha — COMMENTED** [review]
Changed to match requested changes

**Review by AlanKha — COMMENTED** [review]
changed to match mui requests

**Pull request merged**
