### PR TITLE
Manan-Dev/Autocomplete by email, Update Donation form, and Refactor form to use only MUI components

### PR DESCRIPTION
**Pull request by Manan-dev**
# Description

Autocomplete by email, Update Donation form, and Refactor form to use only MUI components

Here is what it looks like now:
image

## Relevant issue(s)

#100 
#65 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have assigned reviewers to this PR

### CODE REVIEW

**Comment by baekay000** [comment]
This looks great. A small fix would be to update the 'Has the donor previously donated' automatically. If the user email is already in the database, that means then that means this is a previous donor.

But, on second thought, do we need that toggle anymore? We might be able to get rid of it altogether. Honestly, it's lacking in functionality right now.

Could you also update the donor name/address/etc to empty if you autofill an email and then delete it? That way that data doesn't get written incorrectly.

**Review by AlanKha — APPROVED** [review]
Looks good to me. Like Kaylee said it would be natural to change prevDonated to yes after a chosen person, but it works great as is.

**Review by alay10 — APPROVED** [review]
Nice job! This page will need quite a lot of validation for what the user has inputted.

**Review by AlanKha — APPROVED** [review]
LGTM

**Pull request merged**
